// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2jcYYCN0DRWQiZERpbaT-l3IfIMA0GDo',
    appId: '1:809319785670:web:b8339cb8dfa94298eda3c7',
    messagingSenderId: '809319785670',
    projectId: 'cashmanager-d8cc1',
    authDomain: 'cashmanager-d8cc1.firebaseapp.com',
    storageBucket: 'cashmanager-d8cc1.appspot.com',
    measurementId: 'G-PMD4VFK3MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwi5piCXM7spn10wxY7UGe7WE7sqR5Auc',
    appId: '1:809319785670:android:70ba60722f114c5aeda3c7',
    messagingSenderId: '809319785670',
    projectId: 'cashmanager-d8cc1',
    storageBucket: 'cashmanager-d8cc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlaU-_hCqfnzJJ9ZpRmLHPMdQrA8dwc_g',
    appId: '1:809319785670:ios:cdc1c12bee741531eda3c7',
    messagingSenderId: '809319785670',
    projectId: 'cashmanager-d8cc1',
    storageBucket: 'cashmanager-d8cc1.appspot.com',
    iosBundleId: 'com.richarddepierre.cashmanager',
  );
}
