FROM node:16

WORKDIR /user/src/app

COPY package*.json ./

RUN npm install -g pnpm
RUN npm install -g dotenv-cli
RUN pnpm install

COPY . .

RUN pnpm generate:prod
RUN pnpm migrate:prod
RUN pnpm build:prod

EXPOSE 3001

CMD [ "pnpm", "start:prod" ]